---
sender:
  default:
    type: zmq
    config:
      address: epgm://br0;239.3.2.1:55555
    tag: statweb-agent
checks:
  http-localhost:
    type: http
    url: http://localhost
    timeout: 2

  http-localhost-dashboard:
    type: http
    url: http://localhost:3000
    timeout: 10
